[root]
    filename = '/data/logs/app/aps/root.log'
    maxBytes = 1024100 # 文件大小为100M
    backupCount = 5 # 备份份数
[other]
    filename = '/data/logs/app/aps/other.log'
    maxBytes = 1024100 # 文件大小为100M
    backupCount = 5 # 备份份数
[apscheduler]
    filename = '/data/logs/app/aps/apscheduler.log'
    maxBytes = 1024100 # 文件大小为100M
    backupCount = 5 # 备份份数